//====================================================================================================
// Base code generated with LeatherGoods - ASF.Business
// Architecture Solutions Foundation
//
// Generated by academic at LeatherGoods V 1.0 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using ASF.Entities;
using ASF.Data;

namespace ASF.Business
{
    public class LocaleResourceKeyBusiness
    {

        /// <summary>
        /// Add method. 
        /// </summary>
        /// <param name="locres"></param>
        /// <returns></returns>
        public LocaleResourceKey Add(LocaleResourceKey locres)
        {
            var locresDac = new LocaleResourceKeyDAC();
            return locresDac.Create(locres);
        }

        /// <summary>
        /// Delete method.
        /// </summary>
        /// <param name="id"></param>
        public void Remove(int id)
        {
            var locresDac = new LocaleResourceKeyDAC();
            locresDac.DeleteById(id);
        }

        /// <summary>
        /// FindAll method.
        /// </summary>
        /// <returns></returns>
        public List<LocaleResourceKey> All()
        {
            var locresDac = new LocaleResourceKeyDAC();
            var result = locresDac.Select();
            return result;
        }

        /// <summary>
        /// Find method.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public LocaleResourceKey Find(int id)
        {
            var locresDac = new LocaleResourceKeyDAC();
            var result = locresDac.SelectById(id);
            return result;
        }

        /// <summary>
        /// Find method by name
        /// </summary>
        /// <param name="name"></param>
        /// <returns></returns>
        public LocaleResourceKey FindByName(string name)
        {
            var locresDac = new LocaleResourceKeyDAC();
            var result = locresDac.SelectByName(name);
            return result;
        }

        /// <summary>
        /// Update method.
        /// </summary>
        /// <param name="locres"></param>
        public void Edit(LocaleResourceKey locres)
        {
            var locresDac = new LocaleResourceKeyDAC();
            locresDac.UpdateById(locres);
        }

    }
}
