//====================================================================================================
// Base code generated with LeatherGoods - ASF.Business
// Architecture Solutions Foundation
//
// Generated by academic at LeatherGoods V 1.0 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using ASF.Entities;
using ASF.Data;

namespace ASF.Business
{
    public class LocaleStringResourceBusiness
    {

        /// <summary>
        /// Add method. 
        /// </summary>
        /// <param name="locstr"></param>
        /// <returns></returns>
        public LocaleStringResource Add(LocaleStringResource locstr)
        {
            var locstrDac = new LocaleStringResourceDAC();
            return locstrDac.Create(locstr);
        }

        /// <summary>
        /// Delete method.
        /// </summary>
        /// <param name="id"></param>
        public void Remove(int id)
        {
            var locstrDac = new LocaleStringResourceDAC();
            locstrDac.DeleteById(id);
        }

        /// <summary>
        /// FindAll method.
        /// </summary>
        /// <returns></returns>
        public List<LocaleStringResource> All()
        {
            var locstrDac = new LocaleStringResourceDAC();
            var result = locstrDac.Select();
            return result;
        }

        /// <summary>
        /// Find method.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public LocaleStringResource Find(int id)
        {
            var locstrDac = new LocaleStringResourceDAC();
            var result = locstrDac.SelectById(id);
            return result;
        }

        /// <summary>
        /// Find method by language
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public List<LocaleStringResource> FindByLang(int id)
        {
            var locstrDac = new LocaleStringResourceDAC();
            var result = locstrDac.SelectByLanguage_Id(id);
            return result;
        }

        /// <summary>
        /// Find method by language and key
        /// </summary>
        /// <param name="idlang"></param>
        /// <param name="idlocres"></param>
        /// <returns></returns>
        public LocaleStringResource FindByLangAndKey(int idlang, int idlocres)
        {
            var locstrDac = new LocaleStringResourceDAC();
            var result = locstrDac.SelectByLanguageAndKey(idlang, idlocres);
            return result;
        }

        /// <summary>
        /// Update method.
        /// </summary>
        /// <param name="locstr"></param>
        public void Edit(LocaleStringResource locstr)
        {
            var locstrDac = new LocaleStringResourceDAC();
            locstrDac.UpdateById(locstr);
        }

    }
}
