//====================================================================================================
// Base code generated with LeatherGoods
// Architecture Solutions Foundation
//
// Generated by academic at LeatherGoods V 1.0 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Runtime.Serialization;
using System.Globalization;

namespace ASF.Entities
{
    /// <summary>
    /// Represents a row of entity data.
    /// </summary>
    [Serializable]
    [DataContract]
    public partial class LocaleStringResource : EntityBase
    {
        /// <summary>
        /// 
        /// </summary>
        [DataMember]
        [DisplayName("Id")]
        [Browsable(false)]
        public int Id { get; set; }

        /// <summary>
        /// TraducciÃ³n
        /// </summary>
        [DataMember]
        [DisplayName("Resource Value")]
        public string ResourceValue { get; set; }

        /// <summary>
        /// Id de la Clave traducida.
        /// </summary>
        [DataMember]
        [DisplayName("Local Resource Key")]
        public int LocaleResourceKey_Id { get; set; }

        /// <summary>
        /// Id del idioma en el que se tradujo.
        /// </summary>
        [DataMember]
        [DisplayName("Language Id")]
        public int Language_Id { get; set; }

    }
}
